name: Secret Bottle
favicon: null
layout_spectrum: 0.10458131600171328
typography_spectrum: 0.74082
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#a5080f'
    - '#3f3f3f'
    - '#bfbfbf'
  brandStrength: 0.8230860973708332
  lightness: 0.27723576757125556
  saturation: 0.3027708698064089
  rhythmicContrast: 0.27429381920956075
purpose: []
